---
- name: Deploy Laravel application to Yandex Cloud
  hosts: 158.160.150.83
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - sqlite3
        - php8.3
        - php8.3-sqlite3
        - php8.3-xml
        - apache2

    - name: Install nvm
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

    - name: Source nvm
      shell: . ~/.bashrc

    - name: Install Node.js
      shell: nvm install 18

    - name: Use Node.js
      shell: nvm use 18

    - name: Install npm dependencies
      shell: npm ci
      args:
        chdir: /home/mrfiftyfifty/user-crud

    - name: Install Composer dependencies
      composer:
        command: install
        working_dir: /home/mrfiftyfifty/user-crud

    - name: Copy .env.example to .env
      copy:
        src: /home/mrfiftyfifty/user-crud/.env.example
        dest: /home/mrfiftyfifty/user-crud/.env

    - name: Create database directory
      file:
        path: /home/mrfiftyfifty/user-crud/database
        state: directory

    - name: Add database path to .env
      lineinfile:
        path: /home/mrfiftyfifty/user-crud/.env
        regexp: "^DB_DATABASE="
        line: "DB_DATABASE=/home/mrfiftyfifty/user-crud/database/database.sqlite"
        create: yes

    - name: Create SQLite database file
      file:
        path: /home/mrfiftyfifty/user-crud/database/database.sqlite
        state: touch

    - name: Generate application key
      shell: php artisan key:generate
      args:
        chdir: /home/mrfiftyfifty/user-crud

    - name: Run migrations
      shell: php artisan migrate
      args:
        chdir: /home/mrfiftyfifty/user-crud

    - name: Set permissions on project folder
      file:
        path: /home/mrfiftyfifty/user-crud
        state: directory
        mode: "0777"
        recurse: yes

    - name: Create Apache config
      copy:
        dest: /etc/apache2/sites-available/hexletJob.conf
        content: |
          <VirtualHost *:80>
              ServerName 158.160.150.83
              DocumentRoot /home/mrfiftyfifty/user-crud/public
              <Directory /home/mrfiftyfifty/user-crud/public>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Enable Apache site
      shell: a2ensite hexletJob

    - name: Enable Apache rewrite module
      shell: a2enmod rewrite

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
