---
- name: Deploy Laravel application to Yandex Cloud
  hosts: 158.160.150.83
  become: yes
  vars:
    ansible_ssh_common_args: "-o ConnectionAttempts=5 -o ConnectTimeout=60"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - docker.io
        - docker-compose

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if Docker container exists
      shell: docker ps -a --filter "name=user-crud-app" --format "{{'{{'}}.Names{{'}}'}}"
      register: container_exists

    - name: Stop existing Docker container
      docker_container:
        name: user-crud-app
        state: stopped
        force_kill: yes
      when: container_exists.stdout != ""

    - name: Remove existing Docker container
      docker_container:
        name: user-crud-app
        state: absent
      when: container_exists.stdout != ""

    - name: Pull the latest Docker image
      docker_image:
        name: devdanilboe/user-crud-app
        tag: latest
        source: pull

    - name: Run the Docker container
      docker_container:
        name: user-crud-app
        image: devdanilboe/user-crud-app:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"

    - name: Set ownership for project directory
      command: chown -R www-data:www-data /home/ty9991peterson/user-crud

    - name: Set permissions for storage directory
      command: chmod -R 755 /home/ty9991peterson/user-crud/storage

    - name: Set permissions for bootstrap/cache directory
      command: chmod -R 755 /home/ty9991peterson/user-crud/bootstrap/cache

    - name: Set permissions for vendor directory
      command: chmod -R 755 /home/ty9991peterson/user-crud/vendor

    - name: Copy .env.example to .env
      command: cp .env.example .env
      args:
        chdir: /home/ty9991peterson/user-crud

    - name: Generate application key
      command: php artisan key:generate
      args:
        chdir: /home/ty9991peterson/user-crud

    - name: Create storage symbolic link
      command: php artisan storage:link
      args:
        chdir: /home/ty9991peterson/user-crud

    - name: Install Composer dependencies
      command: composer install --prefer-dist --no-progress --no-interaction
      args:
        chdir: /home/ty9991peterson/user-crud

    - name: Install npm dependencies
      command: npm ci
      args:
        chdir: /home/ty9991peterson/user-crud

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
